drop table if exists hits;
create table if not exists hits (
   id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   app varchar(255) NOT NULL,
   uri varchar(255) NOT NULL,
   ip varchar(15) NOT NULL,
   timestamp timestamp without time zone,
   CONSTRAINT pk_hit PRIMARY KEY (id)
);