drop table if exists hits;
create table if not exists hits (
   id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   app varchar(255) NOT NULL,
   uri varchar(255) NOT NULL,
   ip varchar(255) NOT NULL,
   whenQueried timestamp without time zone,
   isUnique boolean,
   CONSTRAINT pk_hit PRIMARY KEY (id)
);
